# -*- coding: utf-8 -*-
"""Task4_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEQ0vaWNNXvNZTXHe8VN-9q3aOmMfegw
"""

!pip install -q datasets

from datasets import load_dataset

# Load IMDB dataset
dataset = load_dataset("imdb")

# Select training split
train_data = dataset["train"]

# Print 10 samples
for i in range(10):
    print(f"Sample {i+1}")
    print("Review:", train_data[i]["text"][:200])  # first 200 chars
    print("Label:", train_data[i]["label"])
    print("-" * 50)