# -*- coding: utf-8 -*-
"""Task5_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOP3z7hIgsGVfyi7NsPFPvvObTinO1RW
"""

from google.colab import userdata
os.environ["HF_TOKEN"] = userdata.get('Hftoken')

import os
from openai import OpenAI

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

completion = client.chat.completions.create(
    model="deepseek-ai/DeepSeek-V3.2:novita",
    messages=[
        {
            "role": "user",
            "content": "What is the capital of France?"
        }
    ],
)

print(completion.choices[0].message)

import gradio as gr
from transformers import pipeline

# Load text generation model
generator = pipeline("text-generation", model="gpt2")

# Function for generation
def generate_text(prompt):
    result = generator(prompt, max_length=100, num_return_sequences=1)
    return result[0]["generated_text"]

# Gradio UI
demo = gr.Interface(
    fn=generate_text,
    inputs=gr.Textbox(lines=2, placeholder="Enter your text"),
    outputs="text",
    title="Text Generation App",
    description="AI-powered text generation using Hugging Face"
)

demo.launch()