# -*- coding: utf-8 -*-
"""Task7_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oj-IxWBt4Bboosm86k6EfmhO5pW_h8RU
"""

!pip install -q transformers torch soundfile librosa

from transformers import pipeline

# Load speech recognition pipeline
speech_to_text = pipeline(
    "automatic-speech-recognition",
    model="openai/whisper-small"
)

# Load model directly
from transformers import AutoProcessor, AutoModelForSpeechSeq2Seq

processor = AutoProcessor.from_pretrained("openai/whisper-small")
model = AutoModelForSpeechSeq2Seq.from_pretrained("openai/whisper-small")

!pip install -q openai-whisper

from google.colab import files

uploaded = files.upload()

import whisper

model = whisper.load_model("base")

result = model.transcribe(list(uploaded.keys())[0])

print("Transcribed Text:")
print(result["text"])