# -*- coding: utf-8 -*-
"""Task1_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WS_8Fm3l6CvDqqBW5nfVqFAQPao9zmu7
"""

from transformers import pipeline

# Initialize sentiment analysis pipeline
sentiment_analyzer = pipeline(
    "sentiment-analysis",
    model="siebert/sentiment-roberta-large-english"
)

# Sample text
text = ["I really love using Hugging Face models",
"today was bad morning!"]

# Get sentiment
result = sentiment_analyzer(text)
print(result)