# -*- coding: utf-8 -*-
"""Task2_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkMAn7G3my5EfAdaPGVmc8oziS1FwC5E
"""

pip install transformers torch soundfile

from transformers import pipeline
import soundfile as sf
import numpy as np
import torch

# Load TTS model
tts = pipeline("text-to-speech", model="facebook/mms-tts-eng")

# Input text
text = "Hello,this is text to speech using Hugging Face."

# Generate speech
speech = tts(text)

# Get audio
audio = speech["audio"]

# Convert torch tensor → numpy (if needed)
if isinstance(audio, torch.Tensor):
    audio = audio.cpu().numpy()

# Ensure correct datatype
audio = audio.astype(np.float32)

# Flatten audio
audio = audio.squeeze()

# 🔊 CHANGE AUDIO: increase volume (safe)
audio = audio * 1.2   # 1.0 = normal, >1 louder, <1 quieter

# Save audio as WAV
sf.write(
    "output.wav",
    audio,
    speech["sampling_rate"],
    subtype="PCM_16"
)

print("Audio generated successfully!")